steps:
  count: 30
  delay: 1000

hotel:
  elevator:
    capacity: 3
  spawn-probability:
    ground: 0.6
    other: 0.3
  display:
    column-width:
      floor: 5
      elevator: 24
      persons: 20
